### ISSUE TITLE
BOL: Instructions for infrastructure lab

### ISSUE THREAD

**Issue by jamesrcounts** [jamesrcounts/MCW-Containers-and-DevOps#1]
We need to have words in the Before Hands On Lab file, telling them to download the infrastructure version of the tgz if they are going to do infra edition.

**Comment by vraposo** [comment]
We already have that, it's in a NOTE section between lines 652 and 660. Can you please check whether this solves this issue or not?

**Comment by jamesrcounts** [comment]
Ok, cool i didn't see that.
