### ISSUE TITLE
INFRA: Remove dev task

### ISSUE THREAD

**Issue by jamesrcounts** [jamesrcounts/MCW-Containers-and-DevOps#2]
https://github.com/jamesrcounts/MCW-Containers-and-DevOps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Containers%20and%20DevOps%20-%20Infrastructure%20edition.md#task-5-setup-environment-variables

Here we are still telling them to edit javascript file.  Lets remove.

Update infra edition of the code to already have the right setup (Step 4 should already be done in other words)

Keep the part where they edit the Dockerfile.

**Comment by vraposo** [comment]
Done with commit 2e65712d0bd24e88058e7b8a0da7ba28373b1890.
