### ISSUE TITLE
INFRA: Remove appinsights dev task

### ISSUE THREAD

**Issue by jamesrcounts** [jamesrcounts/MCW-Containers-and-DevOps#5]
https://github.com/jamesrcounts/MCW-Containers-and-DevOps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Containers%20and%20DevOps%20-%20Infrastructure%20edition.md#task-4-perform-a-rolling-update

In this task, we have them edit javascript to add application insights.  Would like to avoid editing `server.js`.  It would be acceptable to still have them edit `production.js` and `development.js` to add thier app insights key.  This applies to both content-web and content-api

Is it possible to provide them with a version of the code that will work even if they don't configure an appinsights key?

Otherwise can we give them a copy of the code that has the appinsights that they can `cp` to the right location instead of editing the javascript?

**Comment by vraposo** [comment]
Done with commit a175b82.
