### ISSUE TITLE
BOTH: Update rolling deployment section to include Release pipeline

### ISSUE THREAD

**Issue by jamesrcounts** [jamesrcounts/MCW-Containers-and-DevOps#6]
If we complete #4 then we do not need step 33 and step 34 in https://github.com/jamesrcounts/MCW-Containers-and-DevOps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Containers%20and%20DevOps%20-%20Infrastructure%20edition.md#task-4-perform-a-rolling-update

Instead at this point in the lab we should guide the students back to AzureDevops so they can see the Release pipeline running.

Then go back to Kubernetes to see the containers deploying, etc.

**Comment by vraposo** [comment]
We actually need step 34, since we only have a Release pipeline for web, not for api.

**Comment by vraposo** [comment]
Should be done with commit cb99fa5, please review changes.

**Comment by jamesrcounts** [comment]
That looks good.  Lets make sure @bingoelzouhery covers this scenario in his testing.
